name: Bot

on:
  schedule:
    # every 4:00 am, MON/WED/FRI (UTC+9)
    # but 7:00 pm, SUN/TUE/THU in UTC
    - cron: '0 19 * * 0,2,4'
  workflow_dispatch:
    inputs:
      update:
        description: 'Run bot'
        required: true
        default: 'Run bot in manually'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'release'
    - name: Set up python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Install python package
      run: |
        pip install selenium==4.1.3
        pip install requests

    - name: Install ubuntu package
      run: |
        sudo apt-get install fonts-unfonts-core
        sudo apt-get install fonts-unfonts-extra
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add
        sudo apt-get install google-chrome-stable
        wget https://chromedriver.storage.googleapis.com/78.0.3904.11/chromedriver_linux64.zip
        unzip ./chromedriver_linux64.zip

    - name: Run bot
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - run: |
        python ./util/bot.py

    - name: Lint
      run: |
        npm ci
        npm run lint

    - name: Commit report
      run: |
          git config --global user.name 'Github Actions'
          git config --global user.email 'joo-na@users.noreply.github.com'
          git add -N db.json
          git diff db.json > git.diff
          [ -s git.diff ] && git add db.json && git commit -m ":construction_worker: automatically updated" && git push || echo "Skip commit"
