name: Release

on:
  push:

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install snapcraft
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            echo "skip"
          elif [ "$RUNNER_OS" == "Windows" ]; then
            echo "skip"
          elif [ "$RUNNER_OS" == "macOS" ]; then
            brew install snapcraft
          fi
        shell: bash
      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}