name: Release

on:
  push:
    tags:
      - v*

jobs:
  build:

    runs-on: ${{ matrix.os }}
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    strategy:
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: npm install
        run: |
          npm install
      - name: electron build
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
              electron build --x64 portable
              npm run dist
          else
            npm run dist
          fi
        shell: bash
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "dist/BojAdvanced*"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}