name: Release

on:
  push:

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macOS-latest]

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install snapcraft
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            echo "skip"
          elif [ "$RUNNER_OS" == "Windows" ]; then
            echo "skip"
          elif [ "$RUNNER_OS" == "macOS" ]; then
            brew install snapcraft
          fi
        shell: bash
      - name: Build + Publish App
        run: |
          npm install
          npm run build:all
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release
        uses: fnkr/github-action-ghr@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_PATH: dist/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}